#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$(cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

screen_hash="$(xrandr --listactivemonitors | sha256sum | awk '{print $1}')"
screen_template="$screen_hash.template.cfg"

echo $screen_template > $DIR/../current.log

if [ ! -f $DIR/../$screen_template ]; then
  cp $DIR/../template.example.cfg $DIR/../$screen_template
fi

$DIR/rand $DIR/../backgrounds $DIR/../$screen_template $DIR/../bg-saved.cfg
nitrogen --restore
