#!/bin/bash

declare -A colors=(
  [Black]='\033[0;30m'
  [Red]='\033[0;31m'
  [Green]='\033[0;32m'
  [Brown_Orange]='\033[0;33m'
  [Blue]='\033[0;34m'
  [Purple]='\033[0;35m'
  [Cyan]='\033[0;36m'
  [Light_Gray]='\033[0;37m'
  [Dark_Gray]='\033[1;30m'
  [Light_Red]='\033[1;31m'
  [Light_Green]='\033[1;32m'
  [Yellow]='\033[1;33m'
  [Light_Blue]='\033[1;34m'
  [Light_Purple]='\033[1;35m'
  [Light_Cyan]='\033[1;36m'
  [White]='\033[1;37m'
  [NC]='\033[0m'
)

function print_color {
  printf "${colors[$2]}${1}${colors[NC]}"
}

export -f print_color

